[package]
name = "derive_builder"
version = "0.0.0"
edition = "2018"
autotests = false
publish = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
workshop-test-runner = { path = "../test-runner" }

[dependencies]
syn = { version="0.15", features=["derive"]}
quote = "0.6"
